theme: jekyll-theme-cayman
name: Paddy Inspector Dataset 
title: Paddy Inspector Dataset
description: A visual and infrared image dataset of paddy diseases and pests. 
github:
  is_project_page: false
